CREATE SCHEMA BOOK_WORM
DEFAULT CHARACTER SET UTF8
DEFAULT COLLATE UTF8_GENERAL_CI;

USE BOOK_WORM;

CREATE TABLE IF NOT EXISTS BOOK_WORM.CATEGORY (
    Category_ID INT(4) NOT NULL AUTO_INCREMENT,
    Category_Name VARCHAR(30) NOT NULL,
    PRIMARY KEY (Category_ID)
);
CREATE TABLE IF NOT EXISTS BOOK_WORM.BOOK (
    ISBN VARCHAR(15) NOT NULL,
    Title VARCHAR(400) NOT NULL,
    Price FLOAT NOT NULL,
    Image LONGTEXT NOT NULL,
    Category_ID INT(4) NOT NULL,
    PRIMARY KEY (ISBN),
    FOREIGN KEY (Category_ID)
        REFERENCES Category (Category_ID)
        ON UPDATE CASCADE
);

CREATE TABLE BOOK_WORM.AUTHOR (
    Author_ID INT(8) NOT NULL AUTO_INCREMENT,
    Author_Name VARCHAR(20) NOT NULL,
    PRIMARY KEY (Author_ID)
);

CREATE TABLE BOOK_WORM.BOOK_AUTHOR (
    ISBN VARCHAR(15) NOT NULL,
    Author_ID INT(8) NOT NULL,
    PRIMARY KEY (ISBN , Author_ID),
    FOREIGN KEY (ISBN)
        REFERENCES BOOK (ISBN)
        ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (Author_ID)
        REFERENCES AUTHOR (Author_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

